---
title: "Assignment 2"
author: "Rex Shen"
date: "9/28/2021"
output: html_document
---

```{r setup, include = FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F)
opts_chunk$set(tidy.opts = list(width.cutoff = 40), tidy = TRUE)
```


```{r, message = FALSE, warning = FALSE}
# Load Packages #
library(tidyverse)
library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(censusapi)
```


```{r}
# Set up System
Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```


```{r, message = FALSE, warning = FALSE}
# State 6 is California
# County 81 is San Mateo County

smc_pop_2020 =
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = c("P1_001N", "NAME") # Total Population P1_001N
  )

smc_pop_2020$BLKGRP = substr(smc_pop_2020$NAME, 25, 25)

smc_pop_2020 = smc_pop_2020 %>% mutate(cbg =
      paste0(state,county, tract, BLKGRP)
  ) %>%
  select(!c(state, county, tract, block, NAME, BLKGRP))

smc_pop_2020 = data.frame(smc_pop_2020)
names(smc_pop_2020)[1] = "Population"

smc_pop_2010 = 
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = c("P001001", "NAME", "BLKGRP") # Total Population P001001
  ) %>%
  mutate(
    cbg =
      paste0(state, county, tract, BLKGRP)
  ) %>% 
  select(!c(state, county, tract, block, NAME, BLKGRP))

smc_pop_2010 = data.frame(smc_pop_2010)
names(smc_pop_2010)[1] = "Population"

####

smc_pop = smc_pop_2020 %>% left_join(
    smc_pop_2010,
    by = "cbg"
  )

names(smc_pop)[1] = "2010Population"
names(smc_pop)[3] = "2020Population"

Column_Order = c("cbg", "2010Population", "2020Population")
smc_pop = smc_pop[, Column_Order]
smc_pop = smc_pop %>% filter(!is.na(`2020Population`))
smc_pop = smc_pop %>% mutate(Absolute_Change = (`2020Population` - `2010Population`))

smc_pop = smc_pop %>% group_by(cbg) %>% summarize(
    Absolute_Change_Final = sum(Absolute_Change, na.rm = T)
  )
```

```{r, message = FALSE, warning = FALSE}
### Create the Plot

smc_blockgroups <- block_groups("CA", "San Mateo", cb = T, progress_bar = F)

pop_pal <- colorNumeric(
  palette = "Blues",
  domain = 
    smc_pop$Absolute_Change_Final
)

leaflet() %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    data = 
      smc_pop %>% 
        left_join(
          smc_blockgroups %>% select(GEOID), 
          by = c("cbg" = "GEOID")
        ) %>% 
        st_as_sf(),
    fillColor = ~pop_pal (Absolute_Change_Final),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(Absolute_Change_Final), 
      " Absolute Change in Population"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = smc_pop,
    pal = pop_pal,
    values = ~Absolute_Change_Final,
    title = "Absolute Change in Population"
  )
```